### ISSUE TITLE
cancel large file upload returns 409 sometimes.

### ISSUE THREAD

**Issue by Anandks1993** [microsoftgraph/msgraph-sdk-javascript#1103]
# Bug Report

## Prerequisites
-   [ ] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

## Description

I am using `LargeFileUploadTask` and `FileUpload` to upload large files to sharepoint site, we needed cancel functionality so I used `cancel` method. It is working fine but sometimes it is returning `409` status and the upload is continued and completed.

![error](https://user-images.githubusercontent.com/26414695/207119568-a55f5b44-df88-4799-8586-ff1bf1134ecd.png)

**Expected behavior:** [What you expected to happen]
Cancel the upload process.

**Actual behavior:** [What actually happened]
Sometimes upload is not cancelled and `409` status is returned which in turn the upload process is getting completed.

SDK Version - v3.0.1

If someone can provide streamlined process of handling cancel process, it would be really helpful.

**Comment by nikithauc** [comment]
@Anandks1993  Thank you for reaching out!

1.  Are you trying to upload to OneDrive or Outlook? Which endpoint are you trying to upload to?
2. When you say that the response is 409 sometimes is there a pattern when this failure occurs?

**Comment by nikithauc** [comment]
> Our requirement is to show the files uploaded to the end user only when admin set the file to display true (like a toggle switch). With list we can use a column to handle this since we are using a drive we are searching for a way to handle this

@Anandks1993 what endpoint are you using to retrieve the list of uploaded files?

**Comment by Anandks1993** [comment]
@nikithauc `/drives/${driveId}/items/root/children` This is the endpoint we are using to fetch the list of uploaded files to a drive. We created a sharepoint drive and uploading files to that drive. As I said earlier we need a way to add a new property `display` and use it to toggle. If you could guide as to how to do it properly it would be very helpful. 

**Workaround way we are going to try:**
1. Create a new sharepoint list and add a `Display` and `Id` fields.
2. First upload the file to the already existing sharepoint drive, once it is successfully uploaded get the `id` of the file.
3. Now create a new list item with the `id` we got and add `Display` default value.

This is the workaround way we thought to use right now.

**Comment by kevklam** [comment]
Apologies as I don't have time to validate each of these steps right now, but here are things you can experiment with:
- Document libraries (drives) *are* lists - you might be able to add the column to the drive itself, instead of creating a separate list to perform this mapping.
- the sites/lists/listitems API surface exposes a 'fields' property which I believe contains custom column values. Every driveItem is also a listItem and can be accessed using this API surface as well (although using siteid/listid/listitemId instead of driveid/itemid)
- There is a 'listItem' navigation property on driveItem that bridges the drives and sites API surfaces. You can do something like GET /drives/{id}/items/root/children?$expand=listItem - this will return the listItem representation of the driveitem including fields.
- You can reduce response size using nested selects/expands, e.g. something like $expand=listItem(select=fields). Support for this type of advanced syntax is a bit spotty, so this might be something you need to play around with to see what works.

**Comment by Anandks1993** [comment]
@kevklam @nikithauc  Thank you for the guidance, I will look into it.
