### ISSUE TITLE
typings files are missing

### ISSUE THREAD

**Issue by itaydemri** [microsoftgraph/msgraph-sdk-javascript#19]
Hello,

*.d.ts files in this package contains a reference to:
`/// <reference path="../../typings/index.d.ts" />`

which is missing after installing package.

using: "msgraph-sdk-javascript": "^0.2.2"

am i missing something? tried to use the microsoftgraph/msgraph-typescript-typings but unfortunately it doesn't support @types yet...

Thanks!

**Comment by dan-silver** [comment]
Good catch @itaydemri . This project still uses typings, so ```typings install``` will populate that folder. But, this won't worked in the published npm package since the typings file doesn't exist.

I've started porting this project away from typings on the ```typings-to-types``` branch.  Both the core files and the typescript sample have been updated.  I'd love feedback on that if you can clone that branch and try it out!

**Comment by dan-silver** [comment]
Also, the migration away from typings is in pull request #20

**Comment by dan-silver** [comment]
#20 has been merged. Please reopen this thread if the types are still an issue.

**Comment by itaydemri** [comment]
Thanks Dan!
it looks much better, however there's a new issue in 0.3.0. i'll open a new issue to address that.

Itay
