### ISSUE TITLE
Question: What's the reason to ask user to import "isomorphic-fetch" himself instead of package it into the SDK

### ISSUE THREAD

**Issue by SLdragon** [microsoftgraph/msgraph-sdk-javascript#405]
From the [wiki](https://github.com/microsoftgraph/msgraph-sdk-javascript/wiki/Migration-from-1.x.x-to-2.x.x) it says:
"This gives more space for the users of the library to take actions regarding polyfills according to their need".

Are there some other reasons for this? 
Seems this is not very common for node js developers to import a dependency library before using a package. 
[AB#8707](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8707)

**Comment by nikithauc** [comment]
> Removed polyfills
In the past our library has included polyfills for fetch and promise. However, doing so adds to the size of our library and many of our customers do not need these polyfills due to their target platform or the fact they already include them in their application. We have now removed the polyfills for fetch and promise. Developers who do still need the polyfills will need to include them explicitly.
https://developer.microsoft.com/en-us/graph/blogs/microsoft-graph-sdk-for-javascript-2-0-0/

The isomorphic-fetch is more of an optional peer dependency for this library.

**Comment by SLdragon** [comment]
OK, thank you very much for your explanation!

**Comment by nikithauc** [comment]
@SLdragon  Can I close this issue ?Do you have more questions or any comments?

**Comment by SLdragon** [comment]
Sure, thank you!

**Comment by zachauten** [comment]
Hi @nikithauc!

I have a question about the explanation you gave, hopefully it's okay if I post it here.

> The isomorphic-fetch is more of an optional peer dependency for this library.

In `Client.ts`, it looks like the first thing the constructor does is call `validatePolyFilling`, which throws an exception if a fetch polyfill isn't installed. 

When you say it's optional, do you mean that the graph sdk needs _a_ polyfill, but it doesn't matter which one, or that you should be able to use this package without fetch at all? If it's the latter, is there a way to initialize Client / use this library without a fetch polyfill?

**Comment by nikithauc** [comment]
@zachauten Thank you for your question!

When I say that use of polyfill is optional it means 
- You can chose any polyfill package that you need.
- You don't need to import a polyfill when working with a browser which has fetch API defined.

Please let me know if you have more questions.

**Comment by zachauten** [comment]
@nikithauc Thanks!
