### ISSUE TITLE
How best for this to call custom Web API and pass-through to MSGraph?

### ISSUE THREAD

**Issue by chauey** [microsoftgraph/msgraph-sdk-javascript#5]
Hello all,

What if we wanted to add some custom data to a Planner Task object for example. The MSGraph does not have that. How can we have this javascript library call a custom WEB API instead, and it can call the MSGraph endpoint instead, and we can add/remove anything as needed? Best way to get/create this WEB API layer that passes the call through and to inject additional properties? Use of swagger would be nice too. thx

**Comment by dan-silver** [comment]
Hey @chauey!  That's a really interesting idea of using the Graph SDKs to also handle custom data that's sent to other APIs.  In order for this discussion to have as many eyes as possible, would you actually mind explaining this idea a bit more and posting on StackOverflow with the tag microsoftgraph?  It will get a lot more attention there from more Microsoft engineers since we're just getting started with this javascript client library.  Thanks!
