### ISSUE TITLE
getStream never sets err parameter on callback

### ISSUE THREAD

**Issue by ddaeschler** [microsoftgraph/msgraph-sdk-javascript#50]
Due to what I believe is a bug here:

https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/b3f23094d6425f1c04a745fd23b215dbc40e3612/src/GraphRequest.ts#L306

A getStream call will never return err as non-null. I'm seeing a 401 authorization error and I'm unable to catch it to refresh my token since err is always null. The result is that I end up streaming the JSON error instead of the file I want to retrieve.

```
client
            .api(`/me/drive/items/${args.fileId}/content`) // path of source file in OneDrive
            .getStream((err, downloadStream) => {
                 //err is null even with a bad token
            });
```

**Comment by casieber** [comment]
Hi, thanks for reaching out.

The SDK expects that the token provided to the authentication provider callback, configured by the consuming application during library initialization, is always a valid access token.

The error you are seeing, an authorization error due to an expired/invalid token, is not something that the SDK was built to handle.

Your application is responsible for refreshing tokens and ensuring that a valid token is always provided.

There are a number of reasonable ways to handle this:

- Use an authentication library such as [ADAL JS](https://github.com/AzureAD/azure-activedirectory-library-for-js), which automatically handles refreshing an access token for you without any application intervention
- Every time you use your retrieved access token, check to see if it is expired or about to expire. If it is, trigger a new token retrieval.
    ```javascript
    function getToken() {
        const cachedToken = this.getCachedToken();

        if (!cachedToken) {
            return this.getNewToken();
        } else {
            return Promise.resolve(cachedToken);
        }
    }

    function getCachedToken() {
        const token = this._token;
        const expiry = this._expiryInMilliseconds;

        if (!this._token) {
            return null;
        }

        // How long before token expiration should we refresh it
        const expiryRefreshOffset = 300000; // 5 min

        if (expiry && (expiry > Date.now() + expiryRefreshOffset)) {
            return token;
        } else {
            this._token = null;
            this._expiryInMilliseconds = null;
            return null;
        }
    }
    ```
- When you first retrieve an access token, check the expiry and use SetTimeout to set up an automatic token refresh shortly before the token expires.
    ```javascript
    function getNewTokenAndSetupRefresh() {
        return this.getNewToken().then(
            token => {
                this._token = token;
                this._expiry = this.getTokenExpiry(token);
                const expiryRefreshOffset = 300000; // 5 min

                // Set up a timeout so before the token expires we get a new one
                setTimeout(
                    () => this.getNewTokenAndSetupRefresh,
                    this._expiry - Date.now() - expiryRefreshOffset
                );
                return token;
            }
        );
    }
    ```

**Comment by ddaeschler** [comment]
Thank you for the response! 

I've worked around this issue another way, and I'm still using the 401 response to trigger a refresh. However, I will definitely be using the expiration checking method in a future revision. Just taking care to make sure I have a few extra seconds to make the call to avoid the race condition between check and execution.

Thank you!
