### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by cjm771** [microsoftgraph/msgraph-sdk-javascript#79]
Hi I am getting a 404 error when querying any api endpoint. Im trying to get calendar events. I have added the following to the application scopes: 
``` js
  var scopes = 'openid profile User.Read Mail.Read Calendars.Read Calendars.Read.Shared';
```
Any idea what might be wrong? thanks.
![image](https://user-images.githubusercontent.com/4239492/41117983-64788416-6a43-11e8-9f8f-13038ab26335.png)

**Comment by MIchaelMainer** [comment]
Thank you for your question about the Microsoft Graph. Since this question is not specific to the JavaScript client library, please post your questions to StackOverflow with the microsoftgraph tag. After you've posted your question on StackOverflow, please provide a link here back to your post. That way, the question will be found by more people -- plus it gives back to the dev community on StackOverflow. 

Make sure you include the following information in your post on StackOverflow:
* What you've tried, your repro steps
* A trace of both the request and response
* Any error messages
* Any settings @
