### ISSUE TITLE
New type definitions to enhance `client.api()` requests

### ISSUE THREAD

**Issue by nikithauc** [microsoftgraph/msgraph-sdk-javascript#979]
Today I am excited to announce the **preview** release of [Microsoft Graph JavaScript Client Library 4.0.0-RestPreview.1](https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/4.0.0-RestPreview.1)

`npm i @microsoft/microsoft-graph-client@4.0.0-RestPreview.1`

> **Note**: The `@microsoft/microsoft-graph-client/v/4.0.0-RestPreview.1` release is not ready for production use. The aim of this release get early feedback from the community.The upcoming releases will contain breaking changes in the design and packaging structure.

## Introducing type definitions to enhance developer experience when using `client.api()` request

With this new feature, when a TypeScript user starts typing a `client.api()` request, on the `.api` step the intellisense will suggest paths, for example, "\me", "\users", "\groups" which are available in Graph API. Once the user selects a path, the intellisense should suggest a list of HTTP methods that are available for the selected path. The type of the response will be known based on the selected path and HTTP method.

![usersPath](https://user-images.githubusercontent.com/23219007/192632110-6fd8e30c-5260-4d32-a0c1-37b003b14196.png)

![getmethod](https://user-images.githubusercontent.com/23219007/192632146-699d8c93-d37f-44c7-b7a5-8b8f6cc97cf8.png)

The goals of the newly generated type definitions are:
- Improve type checking.
- Enhance code completion through intellisense.
- Optimized bundle size as the type definitions are excluded from the bundle.

[Sample applications using @microsoft/microsoft-graph-client@4.0.0-RestPreview.1](https://github.com/microsoftgraph/msgraph-sdk-javascript/tree/feature/4.0.0-rest-typeDefinitions/samples-graphRestClient)
Steps to try out the new typed experience:

1. `npm i @microsoft/microsoft-graph-client@4.0.0-RestPreview.1`
2. Initialize the `Client` and use that instance to get a `graphTypedRestClient`.

```
import {getGraphRestSDKClient, Client, SimpleAuthenticationProvider} from "@microsoft/microsoft-graph-client";

const accessToken = "YOUR_ACCESS_TOKEN";
export const client = Client.init({
    authProvider: new SimpleAuthenticationProvider(async () => {return accessToken} )
})

export const graphTypedRestClient = getGraphRestSDKClient(client);
```

3. Add the import statement based on the request. If the user wants to make a request, let's say, `client.api("/users")`, then the import will be as follows:
```
import "@microsoft/microsoft-graph-client/users"
```

4.
```
import "@microsoft/microsoft-graph-client/users"
import { MicrosoftGraphUser } from "@microsoft/microsoft-graph-types";

 async function getMe(): Promise<MicrosoftGraphUser> {
    const me: MicrosoftGraphUser = await graphTypedRestClient.api("/me").get({}, { $select: "displayName" });
    return me;
}
```

The following import paths are available. The folder structure is based on the [Graph API reference v1.0 table of contents](https://learn.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0)
- @microsoft/microsoft-graph-client/applications
- @microsoft/microsoft-graph-client/calendars
- @microsoft/microsoft-graph-client/changeNotifications
- @microsoft/microsoft-graph-client/compliance
- @microsoft/microsoft-graph-client/crossDeviceExperiences
- @microsoft/microsoft-graph-client/customerBooking
- @microsoft/microsoft-graph-client/customerBooking
- @microsoft/microsoft-graph-client/deviceAppManagement
- @microsoft/microsoft-graph-client/education
- @microsoft/microsoft-graph-client/extensions
- @microsoft/microsoft-graph-client/files
- @microsoft/microsoft-graph-client/groups
- @microsoft/microsoft-graph-client/identityAndAccess
- @microsoft/microsoft-graph-client/mail
- @microsoft/microsoft-graph-client/notes
- @microsoft/microsoft-graph-client/personalContacts
- @microsoft/microsoft-graph-client/reports
- @microsoft/microsoft-graph-client/search
- @microsoft/microsoft-graph-client/security
- @microsoft/microsoft-graph-client/sitesAndLists
- @microsoft/microsoft-graph-client/tasksAndPlans
- @microsoft/microsoft-graph-client/to-doTasks
- @microsoft/microsoft-graph-client/users
- @microsoft/microsoft-graph-client/workbooksAndCharts

> **Note**:
- The type definitions will be packaged separately from the Microsoft Graph JavaScript Client library. The path references will continue to be split into multiple import paths because of the large size of the Graph API. Feedback on and suggestions to optimize the structure and importing are welcome.
- The requests made through the `graphTypedRestClient` in 4.0.0-RestPreview.1 only work for response code `200`, `202` and `application/json` response types. The future releases will contain updates to the response and request handling.

## More changes:

- Allow passing custom `fetch` and removed polyfill requirement
    - Pass a custom implementation of fetch as follows:
    ```
    const client = Client.init({
        authProvider,
        customFetch: fetch
    });
    ```
    - The user can pass a custom `fetch`  implementation or the code defaults to using `node-fetch` or the browser implementation based on the environment.
    - A node user of the Microsoft Graph JavaScript Client library no longer requires to install a polyfill.

- Authentication: Using authentication provider interfaces from [Microsoft Kiota abstractions library](https://www.npmjs.com/package/@microsoft/kiota-abstractions). The following will not be available starting from version 4.0.0.
    - The authentication provider interfaces which are available in version 3.0.0 and below - `IAuthenticationProvider`, `IAuthProvider`.
    - The `msal` and `azure-identity` authproviders. New alternative: [@microsoft/kiota-authentication-azure](https://www.npmjs.com/package/@microsoft/kiota-authentication-azure)

- The following methods will no longer be available start version 4.0.0:

    - `.select()`, `.expand()`, `.count()`, `.search()`, `.top()`, `.query()`, `.skip()`,`.format()`.
        - Use:
        ```
        export interface QueryOptions {
            $select?: string;
            $filter?: string;
            $search?: string;
            $top?: number;
            $count?: boolean;
            $skip?: string;
            $expand?: string;
            $orderby?: string;
            $format?: string;
        }   
        ```
    - `.header()`, `.headers()`

    - Example: 

    Old, that is, 3.0.0 and below

    ```
    client.api("\me").header("key":value).select("displayName").expand("address").get();
    ```
    New: Starting with 4.0.0

    ```
    client.api("\me").get({key:value}, {$select:"displayName", $expand:"address"}).get();
    ```

Try out the new **preview** release of[Microsoft Graph JavaScript Client Library 4.0.0-RestPreview.1](https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/4.0.0-RestPreview. Feedback and suggestions are awaited!!!

**Comment by waldekmastykarz** [comment]
Awesome preview and I really like the approach! Here's some feedback:

### Pros:

- I really like the idea of getting intellisense through URL paths. It's fully aligned with our docs and offers design-time feedback for developers, streamlining their inner loop and helping them avoid runtime errors due to mistyped paths
- I like a lot how we can offer intellisense and design-time type safety through URL paths without significantly increasing the SDK size, which is very important for client-side apps. It also makes it easier to migrate existing apps to benefit from our latest work, comparing to moving to fluent APIs.
- importing paths through the same workload names as listed in the ToC in our docs is great because it's consistent and allows easier lookup of docs for additional information

### Room for improvement:

- in the `.get()` method, I'd prefer to see headers and query options merged into one object, like `.get({ headers: { x: z }, $select: 'displayName'})`. This way, developers don't need to guess which positional argument is what, and if they don't need to specify headers, they don't need to pass an empty object each time they call the API
- we should extend the documentation for `@microsoft/kiota-authentication-azure`, especially around its benefits comparing to using existing libraries like @azure/identity or MSAL which developers already know

**Comment by darrelmiller** [comment]
> importing paths through the same workload names as listed in the ToC in our docs is great because it's consistent and allows easier lookup of docs for additional information

Unfortunately, we cannot do this. The TOC can be changed at any time and our JS SDK cannot without breaking customers.  The path structure is an immutable taxonomy and the only thing that we can rely on to be stable.  Additionally, we shouldn't be asking developers to learn two different hierarchies.  It is the reference docs TOC that should change to match the path structure, not the other way around.

**Comment by waldekmastykarz** [comment]
That's a very good point @darrelmiller and I'm in favor of alignment. If we can align docs ToC with the URL paths, then it would definitely be preferred.

**Comment by plamber** [comment]
Hi,
first of all. You are doing a great job and the SDK as it is today is already a big lifesaver for all our SPA applications.

As a Typescript developer, I am going to love these new enhancements. It will help us write better code without the need to guess return types. I am more of a fan of the fluent design pattern. On the other hand, the tradeoffs you have to make to ensure performance is more important than a fluent design pattern.

Cheers,
Patrick

**Comment by sebastienlevert** [comment]
Thanks for the feedback @plamber. Can you go a bit deeper on what you like about a fluent style? We'd love to make sure we get feedback from both the API-first approach and the fluent approach!

**Comment by plamber** [comment]
Hi @sebastienlevert,
We have been using both the .NET SDK and the JavaScript SDK for several years. When working with the .NET SDK, it feels "more natural and safe" to navigate through the endpoint compared to what we have today in the JavaScript SDK. I can't tell you exactly why I like it more. 

With the new Type checking feature of the JavaScript SDK this "bad feeling" of taking wrong types during development will most likely disappear. After that, I assume it is no more relevant if it is fluent or not.

Hope this helps,
Patrick

**Comment by MIchaelMainer** [comment]
Thank you for the demo. Here's the feedback I captured from it:

1. I think it would be better to abstract getting the typed client by moving the code to get it into the init() method.

```js
export const client = Client.init({
    authProvider: new SimpleAuthenticationProvider(async () => {return accessToken} )
})

export const graphTypedRestClient = getGraphRestSDKClient(client);

// Becomes

export const client = Client.init({
    authProvider: new SimpleAuthenticationProvider(async () => {return accessToken} ),
    isTyped: true
})

```

2. We better have a clear and easily communicated value add for customers if we are going to change the auth provider interface from using MSALAuthenticationProvider from the current library which customers use with MSAL to using the Kiota auth provider. MSAL is familiar, Kiota is not. There are a lot of current dependencies on MSALAuthenticationProvider.
3. Using both the fluent request builder ui versus intellisense style URL path autocomplete both require understanding the underlying http API so that feels like a wash in terms of experience.
4. Looking at the typed client interface side by side with the fluent request builder interface, the typed client interface reads a bit easier. I experience less cognitive load in a themed text editor experience as there are fewer markers, colors, and token to parse. It also maps better to the http documentation.
5. The segmentation feature is nice but will require more thought. I agree with Darrel that we can't use the TOC.

**Comment by appieschot** [comment]
I love the direction of this 👏 and agree with messages before that it is in line with documentation. 

**Improvement **
- The `to-do` feels weird to me, I expected `todo` to align with the graph endpoint called. 

**Questions**
I wonder if there would be a solution for the way we think about retrieving data. Most of the developers internally think like in terms like `get something`, in all these samples we have to think `something get` and while this aligns to the Graph and makes sense in that context, when retrieving data it takes mental energy to swap that in your head, could the SDK help with that scenario as well?

**Comment by sebastienlevert** [comment]
Thanks for the feedback @appieschot! Do you mean like totally ditching the  `api()` method and doing something similar to this : 

`const me = client.get('/me');`

And do something similar for deletes, posts, etc.? The "interesting" thing about this is that it reduces the list of available endpoints as it would be prefiltered to the method called... Thanks for the out-of-the-box thinking here. We're quite happy with the current scheme but it's something to think about!

**Comment by CameronDwyer** [comment]
I love the progress 💖

Pro: Getting type ahead when coding is going to reduce frustration around getting the syntax incorrect and prevent simple typos. 

Con: The developer needs knowledge of which objects to import so not sure how far this goes to increasing the "discoverability" of the Graph API (if that was a purpose of this initiative). One example of where this could actually be a disservice is traversing object types. Imagine I imported @microsoft/microsoft-graph-client/users, I then get type ahead which is awesome because I can see what's available to me at the user level

![image](https://user-images.githubusercontent.com/16345690/196026462-396ef03e-3105-465a-a37d-7a55251fbaa6.png)

But what might not be clear is that this isn't everything that is available to me. Look at that imagine, I don't see /me/mailFolders. Once I import @microsoft/microsoft-graph-client/mail I now get a different type ahead result for /me

![image](https://user-images.githubusercontent.com/16345690/196026540-406d78d0-4231-4c36-b823-b10cb552082e.png)

Same operation in Graph Explorer gives a better "discovery" of all that is available so it's still the go to place for exploring the Graph API.

![image](https://user-images.githubusercontent.com/16345690/196026696-81f992fe-1734-4f2c-a78c-7f239d382488.png)

**Comment by sebastienlevert** [comment]
@CameronDwyer, what would be the best way for us to "slice" the API? What would feel the most natural? Those are questions we are also asking ourselves currently and how we can both deliver a modular SDK while still offering the depth and breadth.

**Comment by sebastienlevert** [comment]
This will be abandoned for a full fluent API. More to come with our Kiota-generated SDKs!
