### ISSUE TITLE
Support for "Extensions" field?

### ISSUE THREAD

**Issue by InternetExplorer8** [microsoftgraph/msgraph-sdk-javascript#98]
It seems that the Extensions field (in my case, Calendar API) is not selectable. The queries were built with /delta. I have seen the following issue: https://stackoverflow.com/questions/47385272/failed-to-get-open-extension-when-use-delta. However, this applies to $expand and filter.

It would be very desirable, otherwise we cannot load custom fields.

Example:
`.select("subject,extensions")`

**Comment by muthurathinam** [comment]
@InternetExplorer8 Thank you for reporting this, I will look into this.

**Comment by MIchaelMainer** [comment]
Extensions are not selectable but are expandable. This is because they are navigation properties, which means extensions are considered entities. If we still do not support delta on extensions, please open a feature request on microsoftgraph.uservoice.com. 

As this isn't a JS client library specific issue, and this has been addressed in StackOverflow, I'll close this.
